version: "3.5"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - ${HTTP_PORT}:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: unless-stopped

volumes:
  influxdb_data:
    name: ${VOLUME_NAME_DATA}
  influxdb_config:
    name: ${VOLUME_NAME_CONFIG}