version: "3.8"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - ${HTTP_PORT}:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=influxdb
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  influxdb_data:
    external: true
    name: ${VOLUME_NAME_DATA}
  influxdb_config:
    external: true
    name: ${VOLUME_NAME_CONFIG}