version: "3.5"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - ${HTTP_PORT}:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana_storage:
    name: ${VOLUME_NAME}