version: "3.8"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - ${HTTP_PORT}:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=grafana
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  grafana_storage:
    name: ${VOLUME_NAME}