version: "3.8"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - ${HTTP_PORT}:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - default
      - traefik-public
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`${TRAEFIK_HOST}`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls.certresolver=desecresolver"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "docker-volume-backup.stop-during-backup=grafana"

volumes:
  grafana_storage:
    name: ${VOLUME_NAME}

networks:
  traefik-public:
    external: true
