version: "3.8"

services:
  evcc:
    command:
      - evcc
    container_name: evcc
    image: evcc/evcc:latest
    ports:
      - ${HTTP_PORT}:7070/tcp
      - ${OCPP_PORT}:8887/tcp
    volumes:
      - data:/root/.evcc
    configs:
      - source: evcc_config
        target: /etc/evcc.yaml
    labels:
      - docker-volume-backup.stop-during-backup=${EVCC_BACKUP_SERVICE_LABEL}
    restart: unless-stopped

volumes:
  data:
    external: true
    name: ${VOLUME_NAME}

configs:
  evcc_config:
    external: true