version: "3.8"

services:
  kicktippbot:
    platform: linux/amd64
    image: ghcr.io/antonengelhardt/kicktipp-bot:amd64
    container_name: kicktipp-bot
    restart: unless-stopped
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure