version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${TOKEN}
    restart: unless-stopped
    secrets:
      - cloudflared_token
    environment:
      TOKEN: /run/secrets/cloudflared_token
secrets:
  cloudflared_token:
    external: true