version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --credentials-file /run/secrets/cloudflared_tunnel_token_file run ${TUNNEL_NAME}
    restart: unless-stopped
    secrets:
      - cloudflared_tunnel_token_file
secrets:
  cloudflared_tunnel_token_file:
    external: true