version: "3.8"

services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    command: agent
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "7007:7007"
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      placement:
        constraints:
          - node.role == manager
