version: "3.8"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "diun_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=${CRON_SCHEDULE}"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_SWARM=true"
      - "DIUN_PROVIDERS_SWARM_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_WEBHOOK_ENDPOINT=${NOTIF_WEBHOOK_ENDPOINT}"
      - "DIUN_NOTIF_WEBHOOK_METHOD=${NOTIF_WEBHOOK_METHOD}"
      - "DIUN_NOTIF_WEBHOOK_HEADERS_CONTENT-TYPE=application/json"
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=diun
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  diun_data:
    name: ${VOLUME_NAME}