version: "3.8"

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
    labels:
      - docker-volume-backup.stop-during-backup=${PAPERLESS_BROKER_BACKUP_SERVICE_LABEL}
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESS_DB}
      POSTGRES_USER: ${POSTGRESS_USER}
      POSTGRES_PASSWORD: /run/secrets/paperless_pg_password
    secrets:
      - paperless_pg_password
    labels:
      - docker-volume-backup.stop-during-backup=${PAPERLESS_DB_BACKUP_SERVICE_LABEL}
    deploy:
      restart_policy:
        condition: on-failure

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - ${HTTP_PORT}:8000
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ${EXPORT_DIR}:/usr/src/paperless/export
      - ${CONSUME_DIR}:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: ${USER_UID}
      USERMAP_GID: ${USER_GID}
      PAPERLESS_SECRET_KEY: /run/secrets/paperless_secret_key
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_APP_TITLE: ${PAPERLESS_APP_TITLE}
      PAPERLESS_CONSUMER_ENABLE_BARCODES: 1
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: 1
      PAPERLESS_CONSUMER_ENABLE_TAG_BARCODE: 1
      PAPERLESS_OCR_DESKEW: 1
      PAPERLESS_CONSUMER_INOTIFY_DELAY: 30
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
    secrets:
      - paperless_secret_key
    labels:
      - docker-volume-backup.stop-during-backup=${PAPERLESS_WEBSERVER_BACKUP_SERVICE_LABEL}
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  data:
    external: true
    name: ${VOLUME_NAME_DATA}
  media:
    external: true
    name: ${VOLUME_NAME_MEDIA}
  pgdata:
    external: true
    name: ${VOLUME_NAME_PG_DATA}
  redisdata:
    external: true
    name: ${VOLUME_NAME_REDIS_DATA}

secrets:
  paperless_pg_password:
    external: true
  paperless_secret_key:
    external: true